services:
  # Redis service
  redis:
    image: redis:latest
    container_name: telebot_redis
    restart: always
    networks:
      - custom-network
    security_opt:
      - seccomp:unconfined # Allow Redis to initialize background jobs
    cap_add:
      - SYS_NICE          # Grant Redis additional privileges if needed
    command: ["redis-server", "--protected-mode", "no"] # Disable protected mode
  # FastAPI app service
  telebot:
    build: .
    image: telebot_backend
    container_name: telebot_backend
    restart: always
    ports:
      - "${DOCKER_PORT:-8001}:8001"
    environment:
      - TZ=Asia/Dhaka
    volumes:
      - ${LOG_DIR}:/app/${LOG_DIR}
      - ./:/app
    networks:
      - custom-network
    depends_on:
      - redis

networks:
  custom-network:
    driver: bridge
