"""ApiKey valid_until column added

Revision ID: a4db790b6d03
Revises: e2fba3a2cc5f
Create Date: 2025-03-22 22:15:04.080189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4db790b6d03'
down_revision: Union[str, None] = 'e2fba3a2cc5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_until', sa.DateTime(timezone=6), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_column('valid_until')

    # ### end Alembic commands ###
